# Workflow to publish Godot HTML5 games to GitHub Pages
#
# Ensure your project is configured for Web export to the path `build/web`.

name: 'Publish to GitHub Pages'

env:
  GODOT_VERSION: 4.4.1

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    container:
      image: barichello/godot-ci:4.1.1 # Still usable, since we override templates

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download HTML5 export templates for Godot ${{ env.GODOT_VERSION }}
        run: |
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          curl -L https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz -o templates.tpz
          tar -xvf templates.tpz -C ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Create staging directory
        run: mkdir -p build/web

      - name: Build Godot project (HTML5)
        run: |
          echo "Exporting project..."
          godot -v --export-release --headless "Web" ../build/web/index.html project/project.godot
          echo "Export complete. Contents:"
          ls -lh ../build/web

      - name: Add coi-service-worker
        run: |
          git clone https://github.com/gzuidhof/coi-serviceworker.git
          mv coi-serviceworker/coi-serviceworker.js build/web/coi-serviceworker.js
          sed -i '3 i <script src="coi-serviceworker.js"></script>' build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
